---
title: "positly_survey_v2"
format: html
editor: visual
---

## Libraries

```{r libraries r}

library(qualtRics)
library(tidyverse)
library(janitor) 
library(stringr)
library(apollo) # for analysis
library(readxl) # for loading design
```

## Load Datasets & Design

```{r load data & design}

qt_labels <- read_survey("~/Downloads/Photovoice/R/Greenspace+Preferences+Survey+-+Positly_July+31,+2026_11.45.zip")

qt_values <- read_survey("~/Downloads/Photovoice/R/Greenspace+Preferences+Survey+-+Positly_July+31,+2026_11.45(1).zip")

design <- read_excel("~/Downloads/Photovoice/R/SCORCH DCE Experimental Design Positly.xlsx", sheet = 2) |> clean_names()

# to maintain original data, create duplicate dataframes to work in from this point forward
df.labs <- qt_labels
df.vals <- qt_values
```

## Rename & Clean Both Datasets

```{r clean datasets}

# drop IP addresses
df.labs <- df.labs |>
  select(-Status)

df.vals <- df.vals |>
  select(-Status)

# janitor::cleannames() tidies & standardizes all column names
df.labs <- df.labs |> clean_names() 
df.vals <- df.vals |> clean_names()

# rename dce questions in both dataframes
rename_map <- c(
  practice_question = "choice_set1",
  a1 = "q2_21",
  a2 = "q3_22",
  a3 = "q4_23",
  a4 = "q5_24",
  a5 = "q6_25",
  a6 = "q7_26",
  a7 = "q8_27",
  a8 = "q9_28",
  a9 = "q10",
  b1 = "q1",
  b2 = "q2_31",
  b3 = "q3_32",
  b4 = "q4_33",
  b5 = "q5_34",
  b6 = "q6_35",
  b7 = "q7_36",
  b8 = "q8_37",
  b9 = "q9_38")

df.labs <- df.labs |> rename(all_of(rename_map))
df.vals <- df.vals |> rename(all_of(rename_map))

# rename other questions
rename_map2 <- c(
  south_az = "sa",
  volunteer = "q144",
  why_sf_text = "q110",
  age = "age_63",
  gender = "gender_64",
  household = "q142",
  household_u18 = "q143",
  yrs_az = "az",
  state = "q111",
  state_51_text = "q111_51_text",
  positly_response_id = "participant_id",
  positly_age = "age_84",
  positly_gender = "gender_85",
  positly_income = "householdincome")

df.labs <- df.labs |> rename(all_of(rename_map2))
df.vals <- df.vals |> rename(all_of(rename_map2))

# use filter() to drop rows that are not from southern az, have an unfinished survey, and did not consent to survey
# use remove_empty() to drop all columns where every single value is NA
df.labs <- df.labs |> 
  filter(finished == TRUE,
         south_az == "Yes",
         consent == "Yes, I consent.") |>
  remove_empty("cols")
df.vals <- df.vals |>
  filter(finished == 1,
         south_az == 1,
         consent == 1) |>
  remove_empty("cols") |>
  mutate(across(where(is.numeric)))

# note: volunteer question was dropped because all responses were NA, question was probably added to survey after positly runs were completed

```

## Recoding & Cleaning for `df.vals` Only

```{r recode & clean df.vals only}

# convert multiple select questions to characters & use stringr::str_detect() to create T/F dummy columns
df.vals <- df.vals |>
  mutate(across(c(race, membership, use, type, mode_transport), as.character)) |>
  mutate(
    race_white            = str_detect(race, "1"),
    race_black            = str_detect(race, "2"),
    race_native_american  = str_detect(race, "3"),
    race_asian            = str_detect(race, "4"),
    race_pacific_islander = str_detect(race, "5"),
    race_other            = str_detect(race, "6"),
    race_prefer           = str_detect(race, "7"),
    membership_community_member    = str_detect(membership, "1"),
    membership_coalition_member    = str_detect(membership, "2"),
    membership_community_org       = str_detect(membership, "3"),
    membership_org_leader          = str_detect(membership, "4"),
    membership_local_gov           = str_detect(membership, "5"),
    membership_policy_maker        = str_detect(membership, "6"),
    membership_greenspace_designer = str_detect(membership, "7"),
    membership_other               = str_detect(membership, "8"),
    membership_prefer              = str_detect(membership, "9"),
    use_exercise_sports = str_detect(use, "1"),
    use_garden          = str_detect(use, "2"),
    use_relax           = str_detect(use, "3"),
    use_social          = str_detect(use, "4"),
    use_other           = str_detect(use, "5"),
    type_city_neighborhood_park   = str_detect(type, "1"),
    type_desert_natural_area      = str_detect(type, "2"),
    type_walk_bike                = str_detect(type, "3"),
    type_community_garden         = str_detect(type, "4"),
    type_private_yard             = str_detect(type, "5"),
    type_school_greenspace        = str_detect(type, "6"),
    type_golf_recreational_area   = str_detect(type, "7"),
    type_other                    = str_detect(type, "8"),
    mode_transport_walk             = str_detect(mode_transport, "1"),
    mode_transport_bike             = str_detect(mode_transport, "2"),
    mode_transport_personal_vehicle = str_detect(mode_transport, "3"),
    mode_transport_public_transit   = str_detect(mode_transport, "4"),
    mode_transport_rideshare_taxi   = str_detect(mode_transport, "5"),
    mode_transport_other            = str_detect(mode_transport, "6"))

# check to see that the above code worked
df.vals |> select(race, starts_with("race_")) |> head(10)
df.vals |> select(membership, starts_with("membership_")) |> head(10)
df.vals |> select(use, starts_with("use_")) |> head(10)
df.vals |> select(type, starts_with("type_")) |> head(10)
df.vals |> select(mode_transport, starts_with("mode_transport_")) |> head(10)

# drop original multi select columns since theyre redundant
df.vals <- df.vals |> 
  select(-c(mode_transport, type, use, race, membership))

# convert remaining numeric columns into factors, excluding metadata & choice tasks
# ! is used to exclude columns 
df.vals <- df.vals |> 
  mutate(across(where(is.numeric) 
                & !matches("^[ab][1-9]$")
                & !c(age, positly_age, household, household_u18, zipcode, duration_in_seconds, progress, q_recaptcha_score, signature_size, practice_question),factor)) 

# in qualtrics, a1 had different answer choice lvls (2/4) then the rest of the choice tasks (1/2). Recode a1 to match the rest.
df.vals <- df.vals |>
  mutate(a1 = case_when(a1 == 2 ~ 1, a1 == 4 ~ 2, TRUE ~ a1))
```

## Reformat `df.vals`

```{r long reformat}

# create a new dataframe to store the reformation
survey_long <- df.vals |>
  select(response_id, matches("^[ab][1-9]$")) |>
  pivot_longer( #reshapes data to long format
    cols = matches("^[ab][1-9]$"),
    names_to = c("block", "choice_situation"),
    names_pattern = "([ab])(\\d+)",
    values_to = "choice") |>
  mutate(
    choice_situation = as.integer(choice_situation),
    block = case_when(block == "a" ~ 1, block == "b" ~ 2)) |>
  filter(!is.na(choice))

# recode survey_long's choice_situation to match the designs continuous numbering
survey_long <- survey_long |>
  mutate(choice_situation = if_else(block == 2, choice_situation + 9L, choice_situation))

# code to check that the choice_situation numbering matches the design
survey_long |> distinct(block, choice_situation) |> arrange(block, choice_situation)
design |> distinct(block, choice_situation) |> arrange(block, choice_situation)
```

## Join `survey_long`, `design`, and demographic data together

```{r join}

# first, create a new dataframe to store the joining of survey_long & design
dce_data <- survey_long |>
  left_join(design, by = c("block", "choice_situation"))

# second, create another dataframe that has specific demographic data pulled from df.vals, excluding demographic data that is irrelevant to analysis 
dce.demo <- df.vals |>
  select(-matches("^[ab][1-9]$"), -matches("_text$"), -practice_question,
         -start_date, -end_date, -progress, -duration_in_seconds, -finished, 
         -recorded_date, -distribution_channel, -user_language, -q_recaptcha_score, 
         -consent, -qc_agree, -comments, -adult, -south_az,
         -starts_with("positly"), -starts_with("signature"))

# third, recode T/F columns to 1/0, respectively
dce.demo <- dce.demo |> 
  mutate(across(where(is.logical), as.integer))

# lastly, create analysis ready dataset
final_data <- dce_data |> 
  left_join(dce.demo, by = "response_id") |> 
  mutate(avail_1 = 1, avail_2 = 1)
```
